env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

# Правила, чтобы еслинт не ругался на отсутсвие импортов.
rules:
  react/react-in-jsx-scope: 0

globals:
  React: true
  PropTypes: true
  renderer: true
  Enzyme: true
